version: 2

sphinx:
  configuration: docs/conf.py

# use conda for the environment
conda:
  environment: docs/environment.yaml

python:
  version: 3.6
  install:
    - requirements: docs/requirements.txt
