{% set data = load_setup_py_data() %}

package:
    name: jungfrau_utils
    version: {{ data['version'] }}

source:
    path: ..

build:
    noarch: python
    number: 0

requirements:
    build:
        - python >=3.7
        - setuptools
    run:
        - python >=3.7
        - h5py >=2.9,<4
        - numpy
        - numba
        - bitshuffle >=0.3.5,<0.4

test:
    source_files:
        - jungfrau_utils/tests
    requires:
        - pytest

about:
    home: https://github.com/paulscherrerinstitute/jungfrau_utils
    summary: {{ data['description'] }}
