{% set data = load_setup_py_data() %}

package:
    name: jungfrau_utils
    version: {{ data['version'] }}

source:
    path: ..

requirements:
    build:
        - python {{ python }}
        - setuptools
    run:
        - python {{ python }}
        - h5py >=2.9
        - numpy
        - numba
        - conda-forge::bitshuffle=0.3.5

test:
    source_files:
        - jungfrau_utils/tests
    requires:
        - pytest

build:
  number: 0
  entry_points:
    - jungfrau_convert_gainmaps = jungfrau_utils.scripts.jungfrau_convert_gainmaps:main
    - jungfrau_run_pedestals = jungfrau_utils.scripts.jungfrau_run_pedestals:main
    - jungfrau_print_pixelmask = jungfrau_utils.scripts.jungfrau_print_pixelmask:main
    - jungfrau_create_pedestals = jungfrau_utils.scripts.jungfrau_create_pedestals:main
    - jungfrau_run = jungfrau_utils.scripts.jungfrau_run:main

about:
   home: https://github.com/paulscherrerinstitute/jungfrau_utils
   summary: {{ data['description'] }}
