package:
    name: jungfrau_utils
    version: 0.0.5
source:
    path: ..

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - pyzmq
        - h5py
        - numpy

build:
  number: 1
  entry_points:
    - jungfrau_convert_gainmaps = jungfrau_utils.scripts.jungfrau_convert_gainmaps:main
    - jungfrau_run_pedestals = jungfrau_utils.scripts.jungfrau_run_pedestals:main
    - jungfrau_print_pixelmask = jungfrau_utils.scripts.jungfrau_print_pixelmask:main
    - jungfrau_create_pedestals = jungfrau_utils.scripts.jungfrau_create_pedestals:main

#about:
#    home: https://github.com/datastreaming/mflow
#    summary: "mflow library."
