{% set data = load_setup_py_data() %}

package:
    name: jungfrau_utils
    version: {{ data['version'] }}

source:
    path: ..

build:
    noarch: python
    number: 0

requirements:
    build:
        - python >=3.8
        - setuptools
    run:
        - python >=3.8
        - h5py >=2.10,<4
        - numpy
        - numba
        - bitshuffle >=0.5

test:
    source_files:
        - tests
    requires:
        - pytest

about:
    home: https://github.com/paulscherrerinstitute/jungfrau_utils
    summary: {{ data['description'] }}
