{% set version_match = load_file_regex(load_file="jungfrau_utils/__init__.py", regex_pattern='__version__ = "(.+?)"') %}
{% set version = version_match[1] %}
{% set pyproject = load_file_data('pyproject.toml') %}

package:
  name: {{ pyproject['project']['name'] }}
  version: {{ version }}

source:
  path: ..

build:
  script: python -m pip install .
  noarch: python

requirements:
  host:
    - python >=3.8
    - hatchling
  run:
    - python >=3.8
    {% for dep in pyproject['project']['dependencies'] %}
    - {{ dep }}
    {% endfor %}

test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest tests

about:
  home: {{ pyproject['project']['urls']['Homepage'] }}
  summary: {{ pyproject['project']['description'] }}
  license: {{ pyproject['project']['license'] }}
  license_file:
  {% for lf in pyproject['project']['license-files'] %}
    - {{ lf }}
  {% endfor %}
